name: Run Tests

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your dependencies file

      - name: Run Python script
        run: python automation.py  # Replace with the path to your Python script
