name: Trigger Lambda Function

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  trigger_lambda:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up AWS credential
        run: |
          echo "krishna"
