name: Trigger Lambda Function

on:
  push:
    branches:
      - master

jobs:
  trigger_lambda:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invoke Lambda function
        run: |
          PAYLOAD='{"message": "Hello, Lambda!"}'
          ENCODED_PAYLOAD=$(echo -n $PAYLOAD | base64)

          aws lambda invoke \
            --function-name automatetesting \
            --payload "$ENCODED_PAYLOAD" \
            response.json
